accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    # path('logout/', views.LoggedOut.as_view(template_name="accounts/logged_out.html"), name='logout'),
    path('accounts/signup/', views.SignUp.as_view(template_name="accounts/signup.html"), name='signup'),
    path('', views.logged_out, name='logout'),

    # path('', views.logged_in, name='logged_in'),
    # path('', views.logged_out, name='logged_out'),

]

m_proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

app_name = 'main'

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mapp.urls', namespace='mapp')),

                  path('accounts/', include('accounts.urls')),
                  # path('__debug__/', include(debug_toolbar.urls)),
                  path("accounts/", include("django.contrib.auth.urls")),  # For django built-in authentication
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mapp/urls.py
from django.urls import path

from . import views
from .views import *

# TODO search for categories,
app_name = 'mapp'

urlpatterns = (

    path('', HomeView.as_view(), name='home'),
    path('<category>', HomeView.as_view(), name='category-home'),
    path('detail/<slug>', AdvertismentDetailView.as_view(), name='detail'),
    path('unbook/<id>', views.unbook, name='unbook'),
    path('assignment/', AssignmentView.as_view(), name='assignments'),
    path('work/', WorkView.as_view(), name='work'),
    path('portfolio/<id>', views.portfolioView, name='portfolio'),
    path('assigm_detail/<id>', views.assigm_detail, name='assigm_detail'),
    path('advertisment_form/',views.adv_view, name='advertisment_form'),
    path('advertisment_form/<id>',views.adv_edit_view, name='advertisment_form_edit'),
    path('delete/<id>',views.delete_adv, name='delete_adv'),
    path('delete_assigm/<id>',views.delete_assigm, name='delete_assigm'),
    path('handyman_adv/',HandymanAdvView.as_view(), name='handyman_adv'),
    path('chat/<user_id>',views.chat, name='chat'),

)

mapp/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from stdimage.models import JPEGField


from m_proj import settings

CATEGORY_CHOICES = (
    ('CA', 'Carpenter'),
    ('PL', 'Plumber'),
    ('EL', 'Electrician'),
    ('AC', 'Installations & Repairs'),
    ('PA', 'Painters'),
    ('CL', 'Cleaning'),
    ('PT', 'Pest Control'),
    ('MC', 'Misc')
)


class Message(models.Model):
    text = models.CharField(max_length=1024)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sender')

    def __str__(self):
        if not self.text:
            return ' '


class Chat(models.Model):
    client = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_client')
    handyman = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_handyman')
    message = models.ManyToManyField(Message)


class Service(models.Model):
    name = models.CharField(max_length=255)
    nameSlug = models.SlugField(unique=True, max_length=255)
    # abbreviation = models.CharField(max_length=3)
    price = models.FloatField()

    def save(self, *args, **kwargs):
        s = slugify(self.name) + str(uuid.uuid4())
        self.nameSlug = s
        print(self.nameSlug)
        super(Service, self).save(*args, **kwargs)

    def __str__(self):
        if self.price != 0:
            return '{} \u20B9{}'.format(self.name, self.price)
        return '{} \u20B9'.format(self.name)

    class Meta:
        db_table = "Service"
        ordering = ['-price']


class Advertisment(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField(default=0)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=3)
    # label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    handyman = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    postdate = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=100)
    task = models.CharField(max_length=200)
    description = models.TextField()
    image = JPEGField(upload_to="", variations={
        'thumbnail': {"width": 400, "height": 250, "crop": True}})
    services = models.ManyToManyField(Service)

    def save(self, *args, **kwargs):
        slug = slugify(self.title) + str(uuid.uuid4())
        self.slug = slug[:50]
        super(Advertisment, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("mapp:detail", kwargs={
            'slug': self.slug
        })

    def is_booked(self, data):
        print('is booked ', data)
        return True

    def getHandymanName(self):
        return self.handyman.get_cache_name()

    def book(self):
        print("reached here book")
        return reverse("mapp:book", kwargs={
            'slug': self.slug
        })

    def unbook(self):
        return reverse("mapp:unbook", kwargs={
            'id': self.id
        })

    def getServices(self):
        return self.services.all()

    def __str__(self):
        return self.title + ' by ' + self.handyman.get_cache_name()

    class Meta:
        db_table = "Advertisment"
        ordering = ['-postdate']


class Assignment(models.Model):
    advertisment_id = models.ForeignKey(Advertisment, on_delete=models.CASCADE)
    handyman = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='handyman')
    client = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='client')
    booking_date = models.DateTimeField(auto_now_add=True)
    price = models.FloatField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    appointment_date = models.DateTimeField(blank=True, null=True)
    durations = models.TimeField(blank=True, null=True)
    completion_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    address = models.CharField(max_length=200, blank=True)
    services = models.ManyToManyField(Service)

    # a = Assignment()
    # a.save()
    # a.services.add(service_obj)
    # a.save(), a.services.all()

    def __str__(self):
        return self.advertisment_id.title + ' for ' + self.client.get_cache_name()

    class Meta:
        db_table = "Assignment"
        ordering = ['-appointment_date']

mapp/views.py
from datetime import datetime, timedelta

import pytz
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from termcolor import cprint

from accounts.models import CustomUser, Dates
from .forms import *
from .models import *


# TODO forms for assigment viewer


# View to chat with handyman or client
def chat(request, **kwargs):
    if request.user.is_handyman:
        client_obj = CustomUser.objects.get(pk=kwargs['user_id'])
        handyman_obj = request.user
        senderName = handyman_obj.get_first_name()
        receiverName = client_obj.get_first_name()
    else:
        client_obj = request.user
        handyman_obj = CustomUser.objects.get(pk=kwargs['user_id'])
        senderName = client_obj.get_first_name()
        receiverName = handyman_obj.get_first_name()

    if request.method == 'POST':
        message = request.POST['message']
        sender = request.user
        message_obj = Message(text=message, sender=sender)
        message_obj.save()
        chat, _ = Chat.objects.get_or_create(client=client_obj, handyman=handyman_obj)
        print(chat)
        chat.message.add(message_obj)
        chat.save()

    try:
        chat = Chat.objects.get(client=client_obj, handyman=handyman_obj)
    except:
        messages = []
        return render(request, 'mapp/chat.html',
                      {'chat_messages': messages, 'sender': senderName, 'reciever': receiverName})

    if chat:
        # Store the messages in the list, True in sender means the user which request page has written this particular
        # message
        messages = [(message.text, str(message.sender_id) == str(request.user.id)) for message in chat.message.all()]

    else:
        messages = []
    print(messages)

    return render(request, 'mapp/chat.html',
                  {'chat_messages': messages, 'sender': senderName, 'reciever': receiverName})


@login_required
# View about the detail info about the handyman
def portfolioView(request, **kwargs):
    print("called for pro")
    print(kwargs['id'])
    # return HttpResponseRedirect(reverse('mapp:portfolio'))
    return render(request, 'mapp/handyman_portfolio.html',
                  {'handyman': CustomUser.objects.get(id=kwargs['id'])})


# View about the detail info of a assignment by both clients and handyman
def assigm_detail(request, **kwargs):
    # print("called for pro")
    # # print(kwargs['id'])
    return render(request, 'mapp/assignment_detail.html',
                  {'assignment': Assignment.objects.get(id=kwargs['id'])})


# View to delete a certain advertisment by handyamn
def delete_adv(request, **kwargs):
    if 'id' in kwargs.keys():
        obj = Advertisment.objects.get(pk=kwargs['id'])
        name = obj.title
        obj.delete()
        messages.warning(request, '"{}" was removed from Advertisments'.format(name))
    return redirect('mapp:handyman_adv')


# View to delete a certain assignment by client or a handyman
def delete_assigm(request, **kwargs):
    if 'id' in kwargs.keys():
        obj = Assignment.objects.get(pk=kwargs['id'])
        name = obj.__str__()
        messages.warning(request, '"{}" was removed from Assignments'.format(name))
    if request.user.is_handyman:
        return redirect('mapp:work')
    return redirect('mapp:assignments')


# View to edit the advertisment by author handyman
def adv_edit_view(request, **kwargs):
    template_name = 'mapp/advertisment_form.html'
    if request.method == 'GET':
        if 'id' in kwargs.keys():
            id = kwargs['id']
            adv_obj = Advertisment.objects.get(pk=id)
            advForm = AdverstimentForm(initial={'title': adv_obj.title,
                                                'image': adv_obj.image,
                                                'task': adv_obj.task,
                                                'description': adv_obj.description,
                                                'category': adv_obj.category,
                                                })
            print(len(adv_obj.services.all()))
            Formset = formset_factory(ServicePriceForm, extra=1)
            formset = Formset(initial=[{'name': x.name, 'price': x.price} for x in adv_obj.services.all()])

            # advForm.fields['title'].widget.attrs('value','aslk')
    elif request.method == 'POST':
        advForm = AdverstimentForm(request.POST, request.FILES)
        formset = service_formset(request.POST)
        print("post")
        # print(advForm)
        if 'id' in kwargs.keys() and formset.is_valid() and advForm.is_bound and len(
                advForm.errors) <= 1:

            print(formset.cleaned_data)
            advForm_data = advForm.cleaned_data
            services = {item.get('name'): item.get('price') for item in formset.cleaned_data
                        if item != None and item.get('name') != None and item.get('price') != None}
            # print(services)

            for item in formset.cleaned_data:
                print(111, item, item.get('name'), item.get('price'))
            # print(advForm_data)

            advObj = Advertisment.objects.get(pk=kwargs['id'])

            if 'title' in advForm_data.keys():
                advObj.title = advForm_data.get('title')
            if 'category' in advForm_data.keys():
                advObj.category = advForm_data.get('category')
            if 'task' in advForm_data.keys():
                advObj.task = advForm_data.get('task')
            if 'description' in advForm_data.keys():
                advObj.description = advForm_data.get('description')
            if 'image' in advForm_data.keys():
                advObj.image = advForm_data.get('image')

            # print(advObj, 11)
            advObj.save()
            # print(services)
            for s in advObj.services.all():
                s.delete()
            advObj.services.clear()

            for k, v in services.items():
                s = Service(name=k, price=v)
                s.save()
                print(k, v)
                advObj.services.add(s)

            advObj.save()
            messages.success(request, 'Advertisment Form Successfully Updated')
            return redirect('mapp:handyman_adv')
        else:
            messages.warning(request, 'There is a problem with the form')
        return redirect('mapp:advertisment_form')

    return render(request, template_name, {
        'form': advForm,
        'formset': formset,
    })


# View to post a new Advertisment by the handyman
def adv_view(request, **kwargs):
    template_name = 'mapp/advertisment_form.html'

    if request.method == 'GET':
        if 'id' in kwargs.keys():
            id = kwargs['id']
            adv_obj = Advertisment.objects.get(pk=id)
            advForm = AdverstimentForm(initial={'title': adv_obj.title,
                                                'image': adv_obj.image,
                                                'task': adv_obj.task,
                                                'description': adv_obj.description,
                                                'category': adv_obj.category,
                                                })
            print(len(adv_obj.services.all()))
            Formset = formset_factory(ServicePriceForm, extra=0)
            formset = Formset(initial=[{'name': x.name, 'price': x.price} for x in adv_obj.services.all()])

            # advForm.fields['title'].widget.attrs('value','aslk')
        else:
            advForm = AdverstimentForm(request.GET or None)
            formset = service_formset()

    elif request.method == 'POST':
        advForm = AdverstimentForm(request.POST, request.FILES)
        formset = service_formset(request.POST)
        print("post")
        # print(advForm)
        if advForm.is_valid() and formset.is_valid():
            print(formset.cleaned_data)
            advForm_data = advForm.cleaned_data
            services = {item.get('name'): item.get('price') for item in formset.cleaned_data
                        if item != None and item.get('name') != None and item.get('price') != None}
            print(services)
            for item in formset.cleaned_data:
                print(111, item, item.get('name'), item.get('price'))
            # print(advForm_data)
            print(type(advForm_data.get('image')))
            advObj = Advertisment(
                title=advForm_data.get('title'),
                handyman=request.user,
                category=advForm_data.get('category'),
                task=advForm_data.get('task'),
                description=advForm_data.get('description'),
                image=advForm_data.get('image')
            )
            print(advObj, 11)
            advObj.save()
            print(services)
            for k, v in services.items():
                s = Service(name=k, price=v)
                s.save()
                print(k, v)
                advObj.services.add(s)

            advObj.save()
            messages.success(request, 'Advertisment Form Successfully saved')
            return redirect('mapp:home')
        else:
            messages.warning(request, 'There is a problem with the form')
        return redirect('mapp:advertisment_form')

    return render(request, template_name, {
        'form': advForm,
        'formset': formset,
    })


class HomeView(ListView):
    paginate_by = 5
    template_name = "mapp/home.html"

    def get_queryset(self):
        try:
            print("#Debug Inside Homeview, get_queryset(): query=", self.request.GET['search'])
            return Advertisment.objects.filter(title__contains=self.request.GET['search'])
        except:
            pass
        try:

templates/mapp/assignment_detail.html
{% extends "mapp/base.html" %}
{% load static %}
{% load get_category %}

{% block extra_head %}
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type='text/javascript'>
        $(document).on("click", ".delete-button", function () {
            var assgim = $(this).data('id');
            console.log(assgim);
            var link = "{% url 'mapp:delete_assigm' id=0 %}".replace('0', assgim);
            $('#confirm-delete').attr('href', link);
        });
    </script>
{% endblock %}

{% block head_title %}
    {{ assignment.advertisment_id.title }} by {{ assignment.handyman.name }}
{% endblock %}

{% block content %}

    <div class="modal fade" id="serviceChooser" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content ">
                <div class="modal-header text-center">
                    <h5 class="modal-title w-100 font-weight-bold">Are you sure</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div align="center">
                    <a id="confirm-delete">
                        <button type="button" class="btn btn-danger">Yes</button>
                    </a>

                    <button type="button" data-dismiss="modal" class="btn btn-white">No</button>
                    {#                    <button  class="close" data-dismiss="modal" class="btn btn-primary">No</button>#}
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12 mb-4  align-items-center">
        <div class="flex-center">
            <h3 class="d-flex flex-center a mr-xl-2 ml-xl-2 mt-4 mb-4">
                <span class="text-xl-center ">{{ assignment.advertisment_id.title }} by {{ assignment.handyman.name }} </span>
            </h3>
            <br>
        </div>
        <div class="flex-center lh-condensed">
            <ul class="list-group w-50  ">
                <li class="list-group-item d-flex border p-1  lh-condensed">
                    <span class="font-weight-bold">Appointment DateTime: &nbsp;</span> {{ assignment.appointment_date }}
                </li>
                <li class="pl-2 p-1 mlist-group-item border  d-flex  lh-condensed">
                    <span class="font-weight-bold">Handyman: &nbsp; </span>{{ assignment.handyman.name }}
                </li>
                <li class="list-group-item d-flex border p-1  lh-condensed">
                    <span class="font-weight-bold">Email: &nbsp; </span>{{ assignment.handyman.email }}
                </li>
                <li class="list-group-item d-flex  border p-1  lh-condensed">
                    <span class="font-weight-bold">Address:&nbsp; </span>{{ assignment.address }}
                </li>
                <li class="list-group-item d-flex  border p-1  lh-condensed">
                    <table>
                        <tr rowspan="2" colspan="2" class="align-items-lg-start">
                            <td><span class="font-weight-bold">Services:</span></td>
                        </tr>
                        {% for item in assignment.services.all %}
                            <tr>
                                <td></td>
                                <td align="left">{{ item.name }}&nbsp;</td>
                                <td align="left">&#8377; {{ item.price }}</td>
                            </tr>
                        {% endfor %}

                    </table>

                </li>
                <li>
                    {% if user.is_handyman %}
                        <a href="{% url 'mapp:chat' user_id=assignment.client_id %}"
                           data-id="chat-button">
                            <button class="btn btn-primary"><i class="fa fa-comment-dots"></i>Chat with Customer</button>
                        </a>
                    {% else %}
                        <a href="{% url 'mapp:chat' user_id=assignment.handyman_id %}"
                           data-id="chat-button">
                            <button class="btn btn-primary"><i class="fa fa-comment-dots"></i>Chat with Handyman</button>
                        </a>
                    {% endif %}
                    <a href="" data-toggle="modal" data-target="#serviceChooser" class="delete-button"
                       data-id="{{ assignment.id }}">
                        <button class="btn btn-danger">Cancel Assignment</button>
                    </a>

                </li>
            </ul>

        </div>
        <br>
        <p align="center">Note: Charges may differ according to the repairs.</p>
    </div>
{% endblock content %}

templates/mapp/detail.html
{% extends "mapp/base.html" %}
{% load get_category %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}
{% block content %}
    {#    Popup for type of booking #}
    <div class="modal fade" id="serviceChooser" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content ">
                <div class="modal-header text-center">
                    <h4 class="modal-title w-100 font-weight-bold">Select the services</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form class="mr-3 ml-3" method="post">
                    {% csrf_token %}
                    {% crispy form %}
                    <div class="modal-footer d-flex justify-content-center">
                        <button class="btn btn-default" type="submit">Book</button>
                    </div>
                    <P>Note: Pricing may vary accordance to actual work and alternation required. Custom pricing is
                        determined according to the task</P>
                </form>
            </div>
        </div>
    </div>

    <main class="mt-5 pt-4">
        <div class="container dark-grey-text mt-5">

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <img src="/media/{{ object.image }}" class="detail-page-cover" alt="no image"/>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <!--Content-->
                    <div class="p-4">

                        <div class="mb-3">
                            <a href="{% url 'mapp:category-home' category=object.category %}">
                                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
                            </a>
                        </div>


                        <p class="lead font-weight-bold">Description</p>

                        <p>{{ object.description }}</p>

                        {% if not  user.is_handyman %}
                            {% is_booked user object object.handyman as booking_status %}
                            {% if  booking_status %}
                                <a href="{{ object.unbook }}" class="btn btn-danger btn-md my-0 p">
                                    Unbook
                                    <i class="fas fa-shopping-cart ml-1"></i>
                                </a>
                            {% else %}
                                {#                            <a href="{{ object.book }}" class="btn btn-primary btn-md my-0 p">#}
                                <a href="" data-toggle="modal" data-target="#serviceChooser"
                                   class="btn btn-primary btn-md my-0 p">
                                    Book
                                    <i class="fas fa-shopping-cart ml-1"></i>
                                </a>
                            {% endif %}
                        {% endif %}


                    </div>
                    <!--Content-->

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            <hr>

            <!--Grid row-->
            <div class="row d-flex justify-content-center wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 text-center">

                    <h4 class="my-4 h4">Handyman</h4>
                    <p class="text-decoration-none">
                        <a href="{% url 'mapp:portfolio' id=object.handyman_id %}">
                            <span >
                            {{ object.handyman.get_cache_name }}</span>
                        </a>
                    </p>
                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            {#      <!--Grid row-->#}
            {#      <div class="row wow fadeIn">#}
            {##}
            {#        <!--Grid column-->#}
            {#        <div class="col-lg-4 col-md-12 mb-4">#}
            {##}
            {#          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">#}
            {##}
            {#        </div>#}
            {#        <!--Grid column-->#}
            {##}
            {#        <!--Grid column-->#}
            {#        <div class="col-lg-4 col-md-6 mb-4">#}
            {##}
            {#          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">#}
            {##}
            {#        </div>#}
            {#        <!--Grid column-->#}
            {##}
            {#        <!--Grid column-->#}
            {#        <div class="col-lg-4 col-md-6 mb-4">#}
            {##}
            {#          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">#}
            {##}
            {#        </div>#}
            {#        <!--Grid column-->#}
            {##}
            {#      </div>#}
            <!--Grid row-->

        </div>
    </main>

{% endblock content %}

templates/mapp/footer.html
<div class="flex-fill" >
    <footer class="page-footer position-static bottom text-center font-small mt-4 wow  ">

        <hr class="my-4">

        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2019 Copyright: Nishan Paudel & Nabin Khadka
        </div>
        <!--/.Copyright-->

    </footer>
</div>

templates/mapp/navbar.html
{% comment %} {% load cart_template_tags %} {% endcomment %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="/">
            <strong class="blue-text">Dwelling</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                {% if user.is_authenticated %}
                    {#          <li class="nav-item">#}
                    {#            <a href="#" class="nav-link waves-effect">#}
                    {#              {% comment %} <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span> {% endcomment %}#}
                    {#              <i class="fas fa-shopping-cart"></i>#}
                    {#              <span class="clearfix d-none d-sm-inline-block"> Cart </span>#}
                    {#            </a>#}
                    {#          </li>#}
                    <li class="nav-item">
                            <span class=" nav-link clearfix  d-none d-sm-inline-block"> Hello {{ user.get_first_name }} </span>
                    </li>

                    {% if not user.is_handyman %}
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'mapp:assignments' %}">
                                <span class="clearfix d-none  d-sm-inline-block"> Assignments </span>
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'mapp:work' %}">
                                <span class="clearfix d-none d-sm-inline-block"> Work </span>
                            </a>
                        </li>

                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link waves-effect text-danger font-weight-bold"
                           href="{% url 'accounts:logout' %}">
                            <span class="clearfix d-none border-danger  d-sm-inline-block"> Logout </span>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'accounts:login' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Login </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'accounts:signup' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>